import React, { useEffect, useRef } from "react";
import Link from "next/link";
import { Box, Button, Container, Stack, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import Episode from "../../components/Episode";

export const getServerSideProps = async (context) => {
  const animeId = context.params.animeId;
  const res = await fetch(
    `https://api.consumet.org/meta/anilist/info/${animeId}`
  );
  const data = await res.json();
  return {
    props: {
      anime: data,
    },
  };
};

const DetailPage = ({ anime }) => {
  const desc = useRef(null);
  useEffect(() => {
    if (desc && anime) {
      desc.current.innerHTML = anime.description;
    }
  }, [desc, anime]);

  return (
    <>
      <Head>
        <title>PokeTv | Anime Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <Box
          sx={{
            width: 1,
            height: 400,
            backgroundImage: `url(${anime.cover ? anime.cover : anime.color})`,
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        ></Box>

        <Container maxWidth="md" disableGutters>
          <Box px={2} py={4}>
            <Typography variant="h4" mb={1}>
              {anime.title?.english ? anime.title.english : anime.title.native}
            </Typography>
            <Typography variant="subtitle1" mb={1}>
              Release date {anime?.releaseDate} | Total episodes{" "}
              {anime?.totalEpisodes}
            </Typography>
            <Typography variant="body2" ref={desc}>
              {anime?.description}
            </Typography>

            <Stack spacing={1} mt={2}>
              <Typography variant="h6">All episodes</Typography>
              {anime?.episodes.map((episode) => (
                <Episode key={episode.id} anime={anime} episode={episode} />
              ))}
            </Stack>
          </Box>
        </Container>
      </Box>
    </>
  );
};

export default DetailPage;
