import Head from "next/head";
import Anime from "../components/Anime";
import { getAnimes } from "../lib/animes";

export const getStaticProps = async () => {
  const animes = await getAnimes();
  return {
    props: {
      animes,
    },
  };
};

export default function Home({ animes }) {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home page</h1>
        <section>
          <h2>Trending Animes</h2>
          <div>
            {animes?.map((anime) => (
              <Anime key={anime.id} anime={anime} />
            ))}
          </div>
        </section>
      </main>
    </>
  );
}
