import Head from "next/head";
import Anime from "../components/Anime";
import { getAnimes } from "../lib/animes";
import { Box, Container, Grid, Typography } from "@mui/material";

export const getStaticProps = async () => {
  const animes = await getAnimes();
  return {
    props: {
      animes,
    },
  };
};

export default function Home({ animes }) {
  return (
    <>
      <Head>
        <title>PokeTv | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth="lg">
        <Box py={2}>
          <Typography variant="h5" mb={2}>
            Trending Animes
          </Typography>
          <Grid container spacing={2}>
            {animes?.map((anime) => (
              <Grid item key={anime.id} xs={6} sm={3} md={2}>
                <Anime anime={anime} />
              </Grid>
            ))}
          </Grid>
        </Box>
      </Container>
    </>
  );
}
